### ISSUE TITLE
org.grails.plugins:spring-security-cas:4.0.0 not published anywhere?

### ISSUE THREAD

**Issue by dylankolson** [grails-plugins/grails-spring-security-cas#87]
Hi - I am trying top upgrade to the latest version but doesn't look like its in maven central? Where can i download the plugin from?

I tried running the "./grailsw install" but it fails with the following error

```spring-security-cas-test1 % ./grailsw install
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at grails.init.Start.main(Start.java:127)
Caused by: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/GeneratedLambda
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	at grails.util.Environment.<clinit>(Environment.groovy:60)
	at org.grails.build.parsing.CommandLineParser.<clinit>(CommandLineParser.java:44)
	at org.grails.cli.GrailsCli.<init>(GrailsCli.groovy:109)
	at org.grails.cli.GrailsCli.main(GrailsCli.groovy:157)
	at org.grails.cli.GrailsCli$main.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at grails.init.RunCommand.main(RunCommand.groovy:35)
	... 5 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.GeneratedLambda
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:677)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:787)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:775)
	... 27 more```

**Comment by dylankolson** [comment]
@puneetbehl thanks for tackling this everything seems to be working for us now
